version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "P@$$word"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - D:\ExchangeRates\data:/var/opt/mssql/data
      - D:\ExchangeRates\log:/var/opt/mssql/log